baseURL = 'http://localhost:3000'
languageCode = 'ja'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = "frla's blog"
theme = 'ananke'

[params]
text_color = 'dark-gray'
background_color_class = 'bg-navy'
author = 'frla'
# favicon = '/images/profile.png'
# site_logo = '/images/profile.png'
